### ISSUE TITLE
improve root device and GPT type probing

### ISSUE THREAD

**Issue by rhdrjones** [Linaro/vmspec-tools#13]
Fedora and CentOS images created with the anaconda installer, launched from virt-install, fail spec validation tests VMSPEC-IMAGE-GPT and VMSPEC-IMAGE-ESP. They should not.

**Comment by suihkulokki** [comment]
This works outside guest but not when running vmspec-validate inside guest:
```
Error: Could not stat device /dev/mapper/fedora-roo - No such file or directory.
VMSPEC-IMAGE-GPT: FAIL
VMSPEC-IMAGE-ESP: FAIL
```
The code incorrectly assumes root partition is on the same block device as the efi partition.

**Comment by suihkulokki** [comment]
The fix in PR appears to work
